### ISSUE TITLE
Upgrade docker-image to Node 6.x

### ISSUE THREAD

**Issue by ivarconr** [finn-no/unleash#126]
Seems to be some issues related to webpack and the node6-docker image. Needs to be investigated further.

**Comment by ivarconr** [comment]
Docker failed the npm install step, with the following error:

```bash
> webpack -p

module.js:442
    throw err;
    ^
Error: Cannot find module 'optimist'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/node_modules/webpack/bin/webpack.js:15:16)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
```

**Comment by ivarconr** [comment]
reloved in #136
